spring:
  datasource:
    url: 'jdbc:h2:mem:testdb;Mode=Oracle'
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    clean-on-validation-error: true

graceful:
  shutdown:
    enabled: false

