spring:
  datasource:
    url: 'jdbc:h2:mem:testdb;Mode=Oracle'
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    clean-on-validation-error: true

graceful:
  shutdown:
    enabled: false

sns:
  topic:
    arn: arn:aws:sns:eu-west-2:000000000000:offender_assessment_events
  endpoint:
    url: http://localstack:4575
  provider: localstack
  region: eu-west-2