apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: trigger-update
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        cron-job: trigger-update
    spec:
      # ttlSecondsAfterFinished: 180
      backoffLimit: 5
      activeDeadlineSeconds: 30
      template:
        metadata:
          labels:
            cron-job: trigger-update
        spec:
          containers:
          - name: trigger-update
            image: radial/busyboxplus:curl
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - curl {{ template "app.fullname" . }}:{{ .Values.image.port }}/events
          restartPolicy: OnFailure