apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.secrets.APPINSIGHTS_INSTRUMENTATIONKEY | b64enc | quote }}
  SNS_AWS_ACCESS_KEY_ID: {{ .Values.secrets.SNS_AWS_ACCESS_KEY_ID | b64enc | quote }}
  SNS_AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.SNS_AWS_SECRET_ACCESS_KEY | b64enc | quote }}
  SNS_TOPIC_ARN: {{ .Values.secrets.SNS_TOPIC_ARN | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.SPRING_DATASOURCE_USERNAME | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.SPRING_DATASOURCE_PASSWORD | b64enc | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.secrets.SPRING_DATASOURCE_URL | b64enc | quote }}
