# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
maxReplicaCount: 2

image:
  repository: quay.io/hmpps/offender-assessment-events
  tag: latest
  port: 8080

cronjob:
  enabled: false

env:
  JAVA_OPTS: "-Xmx512m"
  LAST_ACCESSED_EVENT_DIR: /tmp
