# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
maxReplicaCount: 2

image:
  repository: quay.io/hmpps/offender-assessments-events
  tag: latest
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: assess-event-dev.aks-dev-1.studio-hosting.service.justice.gov.uk
      cert_secret: offender-assessments-events-dev-tls-secret
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
  LAST_ACCESSED_EVENT_FILE: /tmp/last-accessed.properties
  OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

